### ISSUE TITLE
Is this engine still being worked on?

### ISSUE THREAD

**Issue by LiquidWhaleGIT** [Andrettin/Metternich_old#6]
Hi, I would love to develop a game similar to hoi4 and stumbled across this engine while looking for a good engine to develop said game. Are you still working on this engine?

**Comment by Stargazer2019** [comment]
Hello Andrettin, I would like to spouse you to add few more modules in this game engine, do you have a patreon account? or paypal that I would reach you directly? 

The new module I would like to request is about warfare: the new frontline system in Victoria 3 (check the development diary #23). It is so amazing and even inspired me to create my own grand strategy game.

**Comment by Stargazer2019** [comment]
Hello Andrettin, I would like to sponsor you to add and update few more modules in this game engine, do you have a patreon account? or paypal that I would reach you directly?

The new module I would like to ask is about warfare: the new frontline system in Victoria 3 (check the development diary #23). It is so amazing and innovative, I believe it can be the real game changer for grand strategy game. Please let me know if you interested, many thanks.

**Comment by Andrettin** [comment]
@LiquidWhaleGIT Sorry for the (very) late response, I hadn't seen your post before. Unfortunately no, this version of the project is abandoned.

@Stargazer2019 Unfortunately, as above, this project is abandoned. Thanks for the offer though!

I am reworking the project into a TBS grand strategy engine though, you can see it here:
https://github.com/Andrettin/Metternich
